# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  workflow_dispatch: 
  push:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: '21'
    - name: Cache Gradle User Files
      uses: actions/cache@v4
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-user-home
    - name: Cache Gradle Files
      uses: actions/cache@v4
      with:
        path: ./.gradle
        key: ${{ runner.os }}-gradle-file
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Setup Gradle
      run: |
        ./gradlew setup --no-daemon --stacktrace
    - name: Build with Gradle Wrapper
      run: ./gradlew youerJar --no-daemon --stacktrace
    
    - name: Get build timestamp
      id: get-date
      run: |
        echo "datetime=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
        echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT

    - name: Get commit hash
      id: hash
      run: echo "hash=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Youer-1.21.1-server
        path: projects/youer/build/libs/*-server.jar

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./build/libs/*.jar
        body: |
          ### Build Info ℹ️
          - Commit: ${{ steps.hash.outputs.hash }}
          - Build Time: ${{ steps.get-date.outputs.datetime }}
          
          ### Release Notes 📦
          ${{ github.event.head_commit.message }}
          
          ### Notes ⚠️
          - This is an automated CI build
          - Please test thoroughly before using in production
          - For bug reports, please include complete logs and reproduction steps
        tag_name: build-${{ steps.get-date.outputs.date }}-${{ steps.hash.outputs.hash }}
        name: "Build ${{ steps.get-date.outputs.date }} (${{ steps.hash.outputs.hash }})"
        draft: false
        prerelease: true
